$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$htmlPath = Join-Path $root 'sf6-record.html'
$schemaPath = Join-Path $root 'sf6-schema.js'
$agentsPath = Join-Path $root 'AGENTS.md'
$html = Get-Content -LiteralPath $htmlPath -Raw -Encoding UTF8
$schema = Get-Content -LiteralPath $schemaPath -Raw -Encoding UTF8
$agents = Get-Content -LiteralPath $agentsPath -Raw -Encoding UTF8

function Assert-Contains($Text, $Pattern, $Message) {
  if ($Text -notmatch $Pattern) {
    throw $Message
  }
}

function Assert-Fixed($Text, $Needle, $Message) {
  if (-not $Text.Contains($Needle)) {
    throw $Message
  }
}

function Assert-FileFixed($Path, $Needle, $Message) {
  $hit = Select-String -LiteralPath $Path -Pattern $Needle -SimpleMatch -Encoding UTF8
  if (-not $hit) {
    throw $Message
  }
}

function Assert-NotContains($Text, $Pattern, $Message) {
  if ($Text -match $Pattern) {
    throw $Message
  }
}

Assert-Contains $html '<link rel="canonical" href="https://slot-tools\.jp/sf6-record\.html">' 'canonical is missing'
Assert-Fixed $html "STORAGE_KEY" 'storage key is missing'
Assert-Fixed $html "sf6_record_v1" 'storage key value is missing'
Assert-Fixed $html "MACHINE" 'machine export id is missing'
Assert-Fixed $html "L-SF6" 'machine export id value is missing'
Assert-Fixed $html "VERSION" 'version constant is missing'
Assert-Fixed $html "const VERSION='15'" 'version 15 marker is missing'
Assert-Fixed $html '<script src="sf6-schema.js"></script>' 'schema script tag is missing'
Assert-Contains $html "const GAIN_KINDS=\[[^\]]+\]" 'gain kind list is missing'
Assert-Fixed $html "const DC_GAIN_KINDS=GAIN_KINDS.filter" 'DC-only gain kind list is missing'
Assert-Contains $html "const VOICES=\[[^\]]+\]" 'voice list is missing'
Assert-Contains $html "const G_COLORS=\[[^\]]+\]" 'G color list is missing'
Assert-Contains $html "const STAGE_CHOICES=\[[^\]]+\]" 'stage choice list is missing'
Assert-Contains $html "const RARE_KINDS=\[[^\]]+\]" 'rare kind list is missing'
Assert-Contains $html "const HOT_VOICES=new Set\(\[[^\]]+\]\)" 'hot voice list is missing'
Assert-Contains $html "const BONUSES=\[[^\]]+\]" 'bonus list is missing'
Assert-Contains $html "const RANKS=\[[^\]]+\]" 'rank list is missing'
Assert-Contains $html "const ROUND_STARTS=\[[^\]]+\]" 'round start list is missing'
Assert-Contains $html "const OPPONENTS=\[[^\]]+\]" 'opponent list is missing'
Assert-Contains $html "const END_SCREENS=\[[^\]]+\]" 'end screen list is missing'
Assert-Contains $html "const CONTINUES=\[[^\]]+\]" 'continue list is missing'
Assert-Contains $html "const CASH_AMOUNTS=\[[^\]]+\]" 'cash amount list is missing'
Assert-Contains $html "const MONEY_OPS=\[[^\]]+\]" 'money op list is missing'
Assert-Contains $html "const MEDAL_SOURCES=\[[^\]]+\]" 'medal source list is missing'
Assert-Fixed $html "const RELATED_LINKS=" 'related links constant is missing'
Assert-Fixed $html "https://chonborista.com/slot/enta-slot/260280/" 'SF6 related link URL is missing'
Assert-Contains $html "const DEFAULT_LOAN_RATE=50" 'default loan rate is missing'
Assert-Contains $html "const ICATCHES=\[[^\]]+\]" 'icatch list is missing'
Assert-Contains $html "const INITIAL_ICATCHES=\[\.\.\.ICATCHES,'未確認'\]" 'initial icatch choices are missing'
if ((($html -match "const GAIN_KINDS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 5)) -eq $false) { throw 'gain kind count is incorrect' }
Assert-Fixed $html "DC_GAIN_KINDS.forEach" 'DC result sheet must use DC-only kind list'
if ((($html -match "const VOICES=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 8)) -eq $false) { throw 'voice count is incorrect' }
if ((($html -match "const G_COLORS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 3)) -eq $false) { throw 'G color count is incorrect' }
if ((($html -match "const STAGE_CHOICES=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 4)) -eq $false) { throw 'stage count is incorrect' }
if ((($html -match "const RARE_KINDS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 4)) -eq $false) { throw 'rare kind count is incorrect' }
if ((($html -match "const BONUSES=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 3)) -eq $false) { throw 'bonus count is incorrect' }
if ((($html -match "const RANKS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 6)) -eq $false) { throw 'rank count is incorrect' }
if ((($html -match "const ROUND_STARTS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 4)) -eq $false) { throw 'round start count is incorrect' }
if ((($html -match "const OPPONENTS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 6)) -eq $false) { throw 'opponent count is incorrect' }
if ((($html -match "const END_SCREENS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 8)) -eq $false) { throw 'end screen count is incorrect' }
if ((($html -match "const CASH_AMOUNTS=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 3)) -eq $false) { throw 'cash amount count is incorrect' }
if ((($html -match "const ICATCHES=\[([^\]]+)\]") -and (($Matches[1].Split(',').Count) -eq 8)) -eq $false) { throw 'icatch count is incorrect' }
Assert-Contains $html "fbThroughCount" 'FB through counter function is missing'
Assert-Contains $html "hadWin" 'FB interval win flag is missing'
Assert-Contains $html "initialThrough" 'initial through state is missing'
Assert-Contains $html "initialThroughInput" 'initial through input is missing'
Assert-Contains $html "currentStage" 'current stage state is missing'
Assert-Contains $html "currentZenchou" 'current zenchou state is missing'
Assert-Contains $html "currentColor" 'current color state is missing'
Assert-Contains $html "operationBadges" 'operation badge container is missing'
Assert-Contains $html "renderOperationBadges" 'operation badge renderer is missing'
Assert-Contains $html "mode-badge" 'display-only mode badge class is missing'
Assert-Contains $html "currentZenchouBadge" 'current zenchou badge is missing'
Assert-Contains $html "currentColorBadge" 'current color badge is missing'
Assert-Contains $html "recordZenchouEnd" 'zenchou badge end handler is missing'
Assert-Contains $html "recordColorEnd" 'color badge end handler is missing'
Assert-Contains $html "zenchou-in" 'zenchou badge color class is missing'
Assert-Contains $html "color-red" 'color badge red class is missing'
Assert-Contains $html "stage_end" 'stage end record is missing'
Assert-Contains $html "pendingAutoColor" 'pending auto color state is missing'
Assert-Contains $html "autoColorBoundary" 'auto color boundary tracker is missing'
Assert-Contains $html "autoColorResetAt" 'auto color reset cutoff tracker is missing'
Assert-Contains $html "normalizeAutoColorResetAt" 'auto color reset cutoff normalizer is missing'
Assert-Contains $html "autoColorResetAt:normalizeAutoColorResetAt" 'auto color reset cutoff snapshot/export marker is missing'
Assert-Contains $html "state\.autoColorResetAt=Date\.now\(\)" 'LCD overwrite auto color cutoff reset is missing'
Assert-Contains $html "Number\(log\.t\)\|\|0\)>=resetAt" 'auto blue duplicate check should be scoped after cutoff'
Assert-Contains $html "resetAutoColorTrackerToCurrent" 'auto color tracker reset helper is missing'
Assert-Contains $html "cancelPendingAutoColorForObservedColor" 'manual color pending-auto cancellation helper is missing'
Assert-Contains $html "state\.autoColorBoundary=pending\.boundary" 'manual color should mark pending boundary handled'
Assert-Contains $html "state\.pendingAutoColor=null;[\s\S]+state\.battleState='battle'" 'FB hit should clear pending auto color'
Assert-Contains $html "auto:true" 'auto gcolor marker is missing'
Assert-Fixed $html "LOSS_RETURN_COLORS" 'loss return color choices are missing'
Assert-Fixed $html "selectedLossReturnColor" 'loss return color draft is missing'
Assert-Fixed $html "lossReturnColorKinds" 'loss return color chip group is missing'
Assert-Fixed $html "lossReturnColor==='blue'" 'loss return blue branch is missing'
Assert-Fixed $html "addLogDirect({type:'gcolor',color:G_COLORS[0],realG:exitRealG,lcdG:exitLcdG})" 'loss return blue should record gcolor'
Assert-Fixed $html "state.currentColor=G_COLORS[0]" 'loss return blue should light current color badge'
Assert-Fixed $html "state.autoColorBoundary=colorBoundary(exitLcdG)" 'loss return blue should mark boundary handled'
Assert-Fixed $html "ANTEN_PATTERNS" 'anten pattern list is missing'
Assert-Fixed $html "antenLabel" 'anten label helper is missing'
Assert-Fixed $html "SUMAHO_CHARAS" 'sumaho character list is missing'
Assert-Fixed $html "normalizeSumahoChara" 'sumaho normalizer is missing'
Assert-Fixed $html "sumahoLabel" 'sumaho label helper is missing'
if ((($html -match "const SUMAHO_CHARAS=\[([\s\S]*?)\];") -and ([regex]::Matches($Matches[1], "key:").Count -eq 12)) -eq $false) { throw 'sumaho character count is incorrect' }
Assert-Fixed $html "key:'ken',label:'ケン'" 'sumaho Ken identifier mapping is missing'
Assert-Fixed $html "openWtExitSheet" 'WT exit sheet is missing'
Assert-Fixed $html "wtExitAntenKinds" 'WT exit antenna chips are missing'
Assert-Fixed $html "gainAntenKinds" 'DC result antenna chips are missing'
Assert-Fixed $html "gainReturnStageKinds" 'DC result return stage chips are missing'
Assert-Fixed $html "type:'anten'" 'anten record type is missing'
Assert-Fixed $html "type:'icatch'" 'standalone initial icatch record type is missing'
Assert-Fixed $html "initialIcatchSelect" 'initial icatch dropdown is missing'
Assert-Fixed $html "hintKey:'init'" 'initial registration hint key is missing'
Assert-Fixed $html "前回アイキャッチ" 'initial icatch label is missing'
Assert-Contains $html "ceiling" '99 percent rank marker is missing'
Assert-Contains $html "battleStartInfoBtn" 'battle start info sheet button is missing'
Assert-Contains $html "choice-grid-4" '4 column chip grid marker is missing'
Assert-Contains $html "min-height:48px" '48px chip height token is missing'
Assert-Contains $html "font-size:16px" '16px text token is missing'
Assert-Fixed $html "gainKindDisplay" 'gain kind display mapping is missing'
Assert-Fixed $html "choiceChip(gainKindDisplay(label)" 'gain kind display mapping is not used'
Assert-Fixed $html "normalJudgeBtn" 'normal street judge category button is missing'
Assert-Fixed $html "openJudgeSheet" 'street judge sheet is missing'
Assert-Fixed $html "JUDGE_ADD_CHOICES=[10,20,30,50,100]" 'street judge fixed add choices are missing'
Assert-Fixed $html "judgeAddKinds" 'street judge add chip group is missing'
Assert-Fixed $html "recordJudgeAdd" 'street judge instant add recorder is missing'
Assert-NotContains $html "judgeAddG" 'street judge keypad input should be removed'
Assert-NotContains $html "judgeAddDraft" 'street judge add draft should be removed'
Assert-NotContains $html "judgeAntenKinds" 'street judge antenna chips should be removed'
Assert-NotContains $html "selectedJudgeAnten" 'street judge antenna draft should be removed'
Assert-NotContains $html "ジャッジ選択時はボイスを保存しません" 'obsolete judge voice note should be removed from DC result sheet'
Assert-Fixed $html "keypadModal" 'keypad modal is missing'
Assert-Fixed $html "keypadKeys" 'keypad keys are missing'
Assert-Fixed $html "data-keypad" 'keypad button markers are missing'
Assert-Fixed $html "data-keypad-input" 'readonly numeric keypad input marker is missing'
Assert-Fixed $html "readOnly=true" 'readonly numeric input marker is missing'
Assert-Fixed $html "openKeypadForField" 'sheet numeric keypad opener is missing'
Assert-Fixed $html "single-choice-grid" 'single choice two-column grid marker is missing'
Assert-Fixed $html "single-choice-sheet" 'single choice sheet layout marker is missing'
Assert-Fixed $html "VOICE_SKILLS" 'voice skill labels are missing'
Assert-Fixed $html "voice-chip" 'two-line voice chip marker is missing'
Assert-Fixed $html "HINT_REFERENCES" 'hint reference master is missing'
Assert-Fixed $html "sheetHintBtn" 'sheet hint button marker is missing'
Assert-Fixed $html "hintPanel" 'hint panel marker is missing'
Assert-Fixed $html "renderHintPanel" 'hint panel renderer is missing'
Assert-Fixed $html "hintKey:'loss'" 'loss sheet hint key is missing'
Assert-Fixed $html "hintKey:'win'" 'win sheet hint key is missing'
Assert-Fixed $html "hintKey:'start'" 'start info sheet hint key is missing'
Assert-Fixed $html "hintKey:'stage'" 'stage sheet hint key is missing'
Assert-Fixed $html "hintKey:'gcolor'" 'G color sheet hint key is missing'
Assert-Fixed $html "hintKey:'sumaho'" 'sumaho sheet hint key is missing'
Assert-Fixed $html "hintKey:'gain'" 'DC result sheet hint key is missing'
Assert-NotContains $html "hintKey:'judge'" 'street judge hint key should be removed'
Assert-Fixed $html "hintKey:'wtExit'" 'WT exit sheet hint key is missing'
Assert-Fixed $html "hint-section-title" 'hint section title marker is missing'
Assert-Fixed $html "hint-name" 'hint item name marker is missing'
Assert-Fixed $html "hint-text" 'hint description marker is missing'
Assert-Fixed $html "HINT_REFERENCE_FOOTER" 'hint reference footer constant is missing'
Assert-Fixed $html "hint-footer" 'hint footer marker is missing'
function Utf8Text([int[]]$Bytes) {
  return [System.Text.Encoding]::UTF8.GetString([byte[]]$Bytes)
}
Assert-Fixed $html (Utf8Text @(0xE3,0x82,0xAD,0xE3,0x83,0xA3,0xE3,0x83,0x8E,0xE3,0x83,0xB3,0xE3,0x82,0xB9,0xE3,0x83,0x88,0xE3,0x83,0xA9,0xE3,0x82,0xA4,0xE3,0x82,0xAF)) 'cammy voice skill label is missing'
Assert-Fixed $html (Utf8Text @(0xE3,0x81,0x97,0xE3,0x82,0x93,0xE3,0x81,0x8F,0xE3,0x81,0x86,0xE3,0x81,0xAF,0xE3,0x81,0xA9,0xE3,0x81,0x86,0xE3,0x81,0x91,0xE3,0x82,0x93)) 'ryu voice skill kana label is missing'
Assert-Fixed $html (Utf8Text @(0xE3,0x81,0x97,0xE3,0x81,0xA3,0xE3,0x81,0xB7,0xE3,0x81,0x86,0xE3,0x81,0x98,0xE3,0x82,0x93,0xE3,0x82,0x89,0xE3,0x81,0x84,0xE3,0x81,0x8D,0xE3,0x82,0x83,0xE3,0x81,0x8F)) 'ken voice skill kana label is missing'
Assert-Fixed $html (Utf8Text @(0xE3,0x81,0xB6,0xE3,0x81,0x97,0xE3,0x82,0x93,0xE3,0x82,0x89,0xE3,0x82,0x93,0xE3,0x81,0xB3,0xE3,0x82,0x87,0xE3,0x81,0x86,0xE3,0x81,0x97)) 'kimberly voice skill kana label is missing'
Assert-Fixed $html (Utf8Text @(0xE3,0x81,0x92,0xE3,0x81,0xA4,0xE3,0x81,0x8C,0xE3,0x81,0x95,0xE3,0x81,0xBB,0xE3,0x81,0x86)) 'jamie voice skill kana label is missing'
Assert-Fixed $html "startInfoRecordBtn" 'battle start info record button is missing'
Assert-Fixed $html "startInfoConfirmed" 'battle start info pseudo log state is missing'
Assert-Fixed $html "utilityPayoutBtn" 'utility payout button marker is missing'
Assert-Fixed $html "balanceSync" 'balance sync money op is missing'
Assert-Fixed $html "recordMoneyBalanceSync" 'balance sync record handler is missing'
Assert-Fixed $html "openBalanceSyncSheet" 'balance sync sheet is missing'
Assert-Fixed $html "moneyBalanceSyncBtn" 'balance sync record button marker is missing'
Assert-Fixed $html "moneyBalanceCredit" 'balance sync credit input is missing'
Assert-Fixed $html "moneyBalanceMochidama" 'balance sync mochidama input is missing'
Assert-Fixed $html "moneyBalanceSaipurei" 'balance sync saipurei input is missing'
Assert-Fixed $html "currentMochidama" 'current mochidama balance field is missing'
Assert-Fixed $html "currentSaipurei" 'current saipurei balance field is missing'
Assert-Fixed $html "balanceVersion" 'balance model version marker is missing'
Assert-NotContains $html "medalSourceKinds" 'manual medal source chips should be removed'
Assert-NotContains $html "initialMedalInInput" 'initial medal input field should be removed'
Assert-NotContains $html "initialMedalSourceKinds" 'initial medal source chips should be removed'
Assert-Fixed $html "moneyStartRealG" 'initial real G input is missing'
Assert-Fixed $html "moneyStartLcdG" 'initial lcd G input is missing'
Assert-Fixed $html "returnStageKinds" 'loss return stage choices are missing'
Assert-Fixed $html "winCredit" 'win credit input is missing'
Assert-Contains $html "bonusMedals[\s\S]+endScreenSelect[\s\S]+winCredit[\s\S]+勝利を記録" 'win sheet field order should be bonus medals, end screen, credit, record'
Assert-Fixed $html "ending" 'ending bonus value is missing'
Assert-Fixed $html "auto:true" 'auto money diff sync marker is missing'
Assert-Contains $html "startMochidama:m\.startMochidama" 'money after snapshot should include start mochidama'
Assert-Contains $html "startSaipurei:m\.startSaipurei" 'money after snapshot should include start saipurei'
Assert-Contains $html "startRealG:m\.startRealG" 'money after snapshot should include start real G'
Assert-Contains $html "startLcdG:m\.startLcdG" 'money after snapshot should include start lcd G'
Assert-Contains $html "initialMedalInAmount:m\.initialMedalInAmount" 'money after snapshot should include initial medal input'
Assert-Contains $html "initialThrough:nonnegativeInt\(state\.initialThrough\)" 'money after snapshot should include initial through'
Assert-Contains $html "choiceChip" 'non-repaint choice chip helper is missing'
Assert-Contains $html "refreshChoiceGroup" 'non-repaint chip refresh helper is missing'
Assert-Contains $html "wireStageAntenChoices" 'stage antenna delegated wiring is missing'
Assert-Contains $html "data-stage-anten-choice" 'stage antenna choice wiring marker is missing'
Assert-Contains $html "refreshLossSheetMode" 'loss sheet mode should switch without rerendering'
Assert-NotContains $html "previousScrollTop" 'scrollTop restoration should be removed in favor of non-rerender chip selection'
Assert-Contains $html "rankChoices\.append\(choiceChip" 'rank chips should use their own non-repaint group'
Assert-Contains $html "refreshChoiceGroup\(rankChoices,selectedRank\)" 'rank chip refresh should target rank group'
Assert-Contains $html "roundStartChoices\.append\(choiceChip" 'round start chips should use their own non-repaint group'
Assert-Contains $html "refreshChoiceGroup\(roundStartChoices,selectedRoundStart\)" 'round start chip refresh should target round start group'
Assert-NotContains $html "selectedMedalSource" 'manual medal source draft should be removed'
Assert-NotContains $html "selectedInitialMedalSource" 'manual initial medal source draft should be removed'
Assert-Fixed $html "applyKeypad" 'keypad apply handler is missing'
Assert-Fixed $html "renderKeypad" 'keypad render handler is missing'
Assert-Fixed $html "height:min(64dvh, 430px)" 'raised sheet/keypad position token is missing'
Assert-Fixed $html "min-height:34px" 'compact keypad display token is missing'
Assert-Fixed $html ".keypad-panel .sheet-head{display:none}" 'keypad header hidden position token is missing'
Assert-Fixed $html 'dcIn.append' 'drive chance two-line append is missing'
Assert-Fixed $html "btn-line" 'drive chance two-line label marker is missing'
Assert-Fixed $html "dc-label-main" 'drive chance fixed first line marker is missing'
Assert-Fixed $html "dc-label-sub" 'drive chance fixed second line marker is missing'
Assert-Fixed $html "judge-label-main" 'street judge fixed first line marker is missing'
Assert-Fixed $html "judge-label-sub" 'street judge fixed second line marker is missing'
Assert-Fixed $html "justify-content:center" 'close button center alignment is missing'
Assert-Fixed $html "ver:VERSION" 'export version marker is missing'
Assert-Contains $html "winSheetDraft" 'win sheet draft is missing'
Assert-Contains $html "lossSheetDraft" 'loss sheet draft is missing'
Assert-Contains $html "syncWinSheetDraft" 'win sheet input preservation is missing'
Assert-Contains $html "syncLossSheetDraft" 'loss sheet input preservation is missing'
Assert-Contains $html "log\.kind===[^?]+\?null" 'judge voice null guard is missing'
Assert-Contains $html "win:false,bonus:null" 'FB loss bonus null guard is missing'
Assert-Contains $html "currentState" 'currentState persistence is missing'
Assert-Contains $html "battleState" 'battleState persistence is missing'
Assert-Contains $html "sessionMoney" 'session money persistence is missing'
Assert-Fixed $html "dcInBtn" 'drive chance full label marker is missing'
Assert-Fixed $html "normalDcResultBtn" 'DC result label marker is missing'
Assert-Fixed $html "normalJudgeBtn" 'street judge label marker is missing'
Assert-Fixed $html "normalSumahoBtn" 'sumaho grid button marker is missing'
Assert-Fixed $html "moneyCreditBtn" 'balance sync top button marker is missing'
Assert-Fixed $html "残数調整" 'balance sync label is missing'
Assert-Fixed $html "調整を記録" 'balance sync submit label is missing'
Assert-Fixed $html "money-pill.unset" 'uninitialized money display marker is missing'
Assert-Fixed $html "throughCounterPill" 'FB through counter should move to top counter row'
Assert-Contains $html "counter-row[\s\S]+realCounterBtn[\s\S]+lcdCounterBtn[\s\S]+throughCounterPill" 'top counter row should contain real G, lcd G, and FB through'
Assert-Contains $html "money-row[\s\S]+moneyInvestPill[\s\S]+moneyDiffPill" 'money row should contain invest and diff'
Assert-NotContains $html "money-pill`">FBスルー" 'FB through should not remain in money row'
Assert-Fixed $html "diffBreakdown" 'diff breakdown display marker is missing'
Assert-Fixed $html "money-breakdown" 'diff breakdown style marker is missing'
Assert-Fixed $html "intervalDiffBreakdown" 'diff breakdown helper is missing'
Assert-Fixed $html "intervalDiffBreakdownText" 'diff breakdown text helper is missing'
Assert-Fixed $html "intervalDiffDisplay" 'credit-wait diff display helper is missing'
Assert-Fixed $html "balanceSyncRecorded" 'balance sync guard helper is missing'
Assert-Fixed $html "残数調整待ち" 'balance sync wait diff text is missing'
Assert-Fixed $html "（基準）" 'credit wait baseline marker is missing'
Assert-Fixed $html "DIFF_LEGEND_TEXT" 'diff legend text constant is missing'
Assert-Fixed $html "総＝現在総メダル" 'diff legend total description is missing'
Assert-Fixed $html "始＝開始時の持ちメダル＋再プレイ" 'diff legend start description is missing'
Assert-Fixed $html "補＝補正（差枚一致の累積）" 'diff legend adjustment description is missing'
Assert-Fixed $html "#moneyDiffPill{min-height:48px;cursor:pointer}" 'diff legend tap target marker is missing'
Assert-Fixed $html "toast(DIFF_LEGEND_TEXT)" 'diff legend tap handler is missing'
Assert-Fixed $html "parts.total!==0" 'diff breakdown must omit zero current total'
Assert-Fixed $html "parts.start!==0" 'diff breakdown must omit zero starting total'
Assert-Fixed $html "parts.cash!==0" 'diff breakdown must omit zero cash medals'
Assert-NotContains $html "ク\$\{parts\.credit\}\+回\$\{parts\.collect\} −投\$\{parts\.invest\}" 'diff breakdown should no longer force zero-value terms'
Assert-Fixed $html "parts.base!==0" 'diff breakdown must guard initial diff display'
Assert-Fixed $html "parts.adjust!==0" 'diff breakdown must guard diff adjust display'
Assert-Fixed $html "基" 'diff breakdown must show initial diff label'
Assert-Fixed $html "補" 'diff breakdown must show diff adjust label'
Assert-NotContains $html "最初に台へ入れた枚数（例：50）" 'initial medal input wording should be removed'
Assert-NotContains $html "持ち玉・再プレイの残りは、台に入れるたびに「メダル投入」で記録" 'initial medal input supplemental note should be removed'
Assert-NotContains $html "field\('初回投入枚数'" 'old initial medal input label should be removed'
Assert-Fixed $html "店舗情報" 'store information label is missing'
Assert-Fixed $html "店舗情報を保存" 'store information save label is missing'
Assert-NotContains $html "セッション情報" 'session information visible label should be renamed'
Assert-Contains $html "maybePromptInitialMoney" 'initial money auto prompt is missing'
Assert-Contains $html "initialMoneyPromptShown" 'initial money prompt guard is missing'
Assert-Fixed $html 'function openMoneyInitSheet(edit=false)' 'initial money lock signature is missing'
Assert-Fixed $html 'node.disabled=locked' 'initial money locked inputs are missing'
Assert-Fixed $html "locked" 'initial money lock notice is missing'
Assert-Fixed $html "openMoneyInitSheet(true)" 'initial money edit button is missing'
Assert-Fixed $html "battle" 'FB hit should enter battle state'
Assert-Fixed $html "normal" 'FB loss or manual end should return normal state'
Assert-Contains $html "appSnapshot" 'snapshot based undo state is missing'
Assert-Contains $html "restoreSnapshot" 'snapshot restore is missing'
Assert-Contains $html "renderNormalGrid" 'normal fullscreen grid is missing'
Assert-Contains $html "renderBattleGrid" 'battle fullscreen grid is missing'
Assert-Contains $html "normalDcResultBtn" 'normal DC result category button is missing'
Assert-Contains $html "normalJudgeBtn" 'normal street judge category button is missing'
Assert-Contains $html "normalMemoBtn" 'normal memo category button is missing'
Assert-Contains $html "normalSumahoBtn" 'normal sumaho category button is missing'
Assert-Contains $html "normalRareBtn" 'normal rare category button is missing'
Assert-Contains $html "normalGColorBtn" 'normal G color category button is missing'
Assert-Contains $html "normalStageBtn" 'normal stage category button is missing'
Assert-Contains $html "normalZenchouBtn" 'normal zenchou category button is missing'
Assert-Contains $html "openGainSheet" 'DC result sheet is missing'
Assert-Contains $html "openJudgeSheet" 'street judge sheet is missing'
Assert-Contains $html "openSumahoSheet" 'sumaho sheet is missing'
Assert-Fixed $html "sumahoCharaSelect" 'sumaho dropdown is missing'
Assert-Fixed $html "sumahoRecordBtn" 'sumaho record button is missing'
Assert-Fixed $html "recordSumaho" 'sumaho recorder is missing'
Assert-Contains $html "openMemoSheet" 'memo sheet is missing'
Assert-Contains $html "openRareSheet" 'rare sheet is missing'
Assert-Contains $html "openGColorSheet" 'G color sheet is missing'
Assert-Contains $html "openStageSheet" 'stage sheet is missing'
Assert-Fixed $html "stageAntenKinds" 'stage antenna chips are missing'
Assert-Contains $html "function openStageSheet\(\)[\s\S]+body\.append\(choices\);[\s\S]+暗転パターン（任意）[\s\S]+body\.append\(antenChoices\);" 'stage sheet should list stage choices before antenna choices'
Assert-Contains $html "function openStageSheet\(\)[\s\S]+wireStageAntenChoices\(antenChoices\)[\s\S]+btn\.dataset\.stageAntenChoice=item\.key" 'stage antenna chips should be wired after sheet reorder'
Assert-Contains $html "if\(anten\)applyAnten\(anten,snap\)" 'stage sheet should record antenna in the same undo'
Assert-Contains $html "openZenchouSheet" 'zenchou sheet is missing'
Assert-Fixed $html "openSheet" 'sheet open helper call is missing'
Assert-Fixed $html "openGColorSheet" 'G color sheet title is missing'
Assert-Fixed $html "openRareSheet" 'rare sheet title is missing'
Assert-Fixed $html "openStageSheet" 'stage sheet title is missing'
Assert-Fixed $html "openZenchouSheet" 'zenchou sheet title is missing'
Assert-Contains $html "RANK_RATE_LABELS" 'rank rate label mapping is missing'
Assert-Contains $html "50%" 'rank 50 percent label is missing'
Assert-Contains $html "88%" 'rank 88 percent label is missing'
Assert-Contains $html "ROUND_START_LABELS" 'round start display label mapping is missing'
Assert-Contains $html "blue-default" 'round start blue description marker is missing'
Assert-Contains $html "green-upper" 'round start green description marker is missing'
Assert-Contains $html "closeAfter:true" 'single-select sheet auto close marker is missing'
Assert-Fixed $html "DEFAULT_RETURN_COLOR" 'zenchou out linked G color record is missing'
Assert-Contains $html "DEFAULT_RETURN_COLOR=G_COLORS\[2\]" 'default return color constant is missing'
Assert-Contains $html "color:DEFAULT_RETURN_COLOR" 'zenchou out default return color is missing'
Assert-Contains $html "chip\.green-text" 'green chip text class is missing'
Assert-Fixed $html "green-text" 'round start green text mapping is missing'
Assert-Contains $html "isBattleLocked" 'battle G operation lock helper is missing'
Assert-Contains $html "BATTLE_STEP_LOCK_TOAST" 'battle step lock toast is missing'
Assert-Contains $html "BATTLE_ADJUST_LOCK_TOAST" 'battle adjust lock toast is missing'
Assert-Fixed $html "data-step" 'battle step disabled rendering is missing'
Assert-Fixed $html "data-adjust" 'battle adjust disabled rendering is missing'
Assert-NotContains $html 'stepUndoBtn[\s\S]{0,60}disabled=locked' 'step undo button should not be battle locked'
Assert-NotContains $html 'function undoStep\(\)\{[\s\S]{0,120}BATTLE_STEP_LOCK_TOAST' 'step undo handler should not be battle locked'
Assert-Contains $html 'closeSheet\(\);[\s\S]+restoreSnapshot\(action\.before\)' 'record undo should close sheet and restore snapshot'
Assert-Contains $html "lcd-attention" 'LCD update reminder class is missing'
Assert-Contains $html "stepHistory" 'step undo history is missing'
Assert-Contains $html 'data-step="10"' '+10 step button is missing'
Assert-Contains $html "stepUndoBtn" 'step undo button is missing'
Assert-NotContains $html 'adjustPanel|adjustValue|data-adjust-step' 'legacy adjust panel should be removed'
Assert-Contains $html "downloadJsonBtn" 'download JSON button is missing'
Assert-Contains $html "URL\.revokeObjectURL" 'download URL cleanup is missing'
Assert-Fixed $html "new Blob" 'JSON blob export is missing'
Assert-Contains $html "sf6-record_" 'download filename prefix is missing'
Assert-Contains $html "dataset\.lastFilename" 'download filename test marker is missing'
Assert-Fixed $html "gcolor" 'gcolor record is missing'
Assert-Fixed $html "anten" 'anten record is missing'
Assert-Fixed $html "sumaho" 'sumaho record is missing'
Assert-Fixed $html "stage_sel" 'stage selection record is missing'
Assert-Fixed $html "rare" 'rare record is missing'
Assert-Fixed $html "dcin" 'dcin record is missing'
Assert-Fixed $html "fbhit" 'fbhit record is missing'
Assert-Fixed $html "continue" 'continue record is missing'
Assert-Contains $html "latestFbHit" 'latest FB hit helper is missing'
Assert-Contains $html "kiteiG" 'kiteiG field is missing'
Assert-Contains $html "rankKinds" 'rank chips are missing'
Assert-Contains $html "roundStartKinds" 'round start chips are missing'
Assert-Contains $html "opponentText" 'opponent field is missing'
Assert-Fixed $html "opponentText" 'opponent dropdown is missing'
Assert-Contains $html "endScreenSelect" 'end screen dropdown is missing'
Assert-Contains $html "bonusMedals" 'bonus medals field is missing'
Assert-Contains $html "roundStart" 'roundStart field is missing'
Assert-Contains $html "continue:" 'continue field is missing'
Assert-Contains $html "fbExitLcdG" 'FB exit lcd field is missing'
Assert-Contains $html "fbExitRealG" 'FB exit real field is missing'
Assert-Contains $html "exitRealG" 'FB exit real model field is missing'
Assert-Contains $html "fbExitCredit" 'FB exit credit field is missing'
Assert-Contains $html "fbLossFields" 'FB loss-only field group is missing'
Assert-Contains $html "moneyLoanBtn" 'money loan button is missing'
Assert-Contains $html "moneyDepositBtn" 'money deposit button is missing'
Assert-Contains $html "moneyCreditBtn" 'money balance sync button is missing'
Assert-Contains $html "openMoneyInitSheet" 'money init sheet is missing'
Assert-Contains $html "openMoneyDepositSheet" 'money deposit sheet is missing'
Assert-Contains $html "openBalanceSyncSheet" 'money balance sync sheet is missing'
Assert-NotContains $html "openMoneyCreditSheet" 'old credit sheet should be removed'
Assert-NotContains $html "openMoneyMedalUseSheet" 'old medal input sheet should be removed'
Assert-Contains $html "openMoneyDiffSyncSheet" 'money diff sync sheet is missing'
Assert-Contains $html "openMoneyCollectSheet" 'money collect sheet is missing'
Assert-Contains $html "recordMoneyInit" 'money init recorder is missing'
Assert-Contains $html "recordMoneyLoan" 'money loan recorder is missing'
Assert-Contains $html "recordMoneyDeposit" 'money deposit recorder is missing'
Assert-Contains $html "recordMoneyBalanceSync" 'money balance sync recorder is missing'
Assert-NotContains $html "recordMoneyCreditUpdate" 'old credit update recorder should be removed'
Assert-NotContains $html "recordMoneyMedalIn" 'old medal input recorder should be removed'
Assert-Contains $html "recordMoneyDiffSync" 'money diff sync recorder is missing'
Assert-Contains $html "recordMoneyCollectEnd" 'money collect end recorder is missing'
Assert-Fixed $html "relatedLinks" 'related links section is missing'
Assert-Fixed $html "target='_blank'" 'related links must open in a new tab'
Assert-Fixed $html "rel='noopener noreferrer'" 'related links rel attribute is missing'
Assert-Fixed $html "related-link" 'related link button class is missing'
Assert-Fixed $html "item.label" 'related link label rendering is missing'
Assert-Fixed $html "money" 'money record type is missing'
Assert-Fixed $html "loan" 'money loan op is missing'
Assert-Fixed $html "balanceSync" 'money balance sync op is missing'
Assert-Fixed $html "creditUpdate" 'legacy money credit update op compatibility is missing'
Assert-Fixed $html "diffSync" 'money diff sync op is missing'
Assert-Fixed $html "collectEnd" 'money collect end op is missing'
Assert-Contains $html "intervalDiffValue" 'interval diff calculation is missing'
Assert-Contains $html "currentTotalMedals" 'current total medals calculation is missing'
Assert-Contains $html "cashInvestedMedals" 'cash invested medals calculation is missing'
Assert-Contains $html "startingMedals" 'starting medals subtraction helper is missing'
Assert-Contains $html "m\.initialDiff\+currentTotalMedals\(m\)-startingMedals\(m\)-cashInvestedMedals\(m\)\+m\.diffAdjust" 'interval diff should use snapshot total formula'
Assert-Contains $html "collect\+credit\+currentWallet-startingMedals\(m\)-cashMedals" 'money summary should use snapshot wallet formula'
Assert-Contains $html "moneySummary" 'money summary helper is missing'
Assert-Fixed $html "cash" 'cash record compatibility is missing'
Assert-Fixed $html "collect" 'collect record compatibility is missing'
Assert-NotContains $html 'cashKinds|cashBtn|collectBtn' 'legacy cash/collect entry UI should not be present'
Assert-Contains $html "icatchKinds" 'icatch chips are missing'
Assert-Contains $html "selectedIcatch" 'icatch selection state is missing'
Assert-Contains $html "icatch:null" 'FB win icatch null guard is missing'
Assert-Contains $html "icatchNote:null" 'FB win icatch note null guard is missing'
Assert-Fixed $html "textContent" 'textContent helper is missing'
Assert-Fixed $html "setText" 'memo log must use textContent helper'
Assert-Fixed $html "JSON.stringify" 'JSON export formatting is missing'
Assert-Fixed $html "SF6RecordApp" 'test hook is missing'
Assert-Contains $html "exportData" 'export data test hook is missing'
Assert-Contains $html "normalizeSf6Export" 'schema normalizer integration is missing'
Assert-Contains $html "inputMode='none'" 'OS keyboard suppression marker is missing'
Assert-Contains $html "resetTimer" 'two-tap reset state is missing'
Assert-Fixed $html "resetDraftState" 'reset should clear draft and internal transient state'
Assert-Contains $html "state=defaultState\(\);[\s\S]+resetDraftState\(\);[\s\S]+localStorage\.removeItem\(STORAGE_KEY\)" 'reset should clear state, drafts, and localStorage together'
Assert-Contains $html "if\(!moneyInitialized\(\)\)\{[\s\S]+初期登録待ち" 'money summary should not render stale balances before initialization'
Assert-Contains $html "lcdG" 'lcd field is missing'
Assert-NotContains $html "statGap" 'gap display should be removed'
Assert-NotContains $html 'FB_TRIGGERS|fbTriggers|selectedFbTrig|trig:' 'FB trigger field should be removed'
Assert-NotContains $html "innerHTML\s*=" 'innerHTML assignment should not be used on user-visible logs'
Assert-NotContains $html 'display:\s*grid|grid-template' 'CSS grid should not be used in this page'

$index = Get-Content -LiteralPath (Join-Path $root 'index.html') -Raw -Encoding UTF8
$sitemap = Get-Content -LiteralPath (Join-Path $root 'sitemap.xml') -Raw -Encoding UTF8
Assert-Contains $index "sf6-record\.html" 'index link is missing'
Assert-Contains $sitemap "https://slot-tools\.jp/sf6-record\.html" 'sitemap link is missing'

Assert-Fixed $schema "normalizeSf6Export" 'normalizeSf6Export definition is missing'
Assert-Fixed $schema "SCHEMA_VERSION" 'schema version constant is missing'
Assert-Fixed $schema "SCHEMA_VERSION='15'" 'schema version 15 marker is missing'
Assert-Fixed $schema "ver:SCHEMA_VERSION" 'schema output version is missing'
Assert-Fixed $schema "legacy_trig" 'legacy trig preservation is missing'
Assert-Fixed $schema "currentState:normalizeCurrentState" 'currentState default normalization is missing'
Assert-Fixed $schema "battleState:normalizeBattleState" 'battleState default normalization is missing'
Assert-Fixed $schema "initialThrough" 'initial through normalization is missing'
Assert-Fixed $schema "currentStage" 'current stage normalization is missing'
Assert-Fixed $schema "currentZenchou" 'current zenchou normalization is missing'
Assert-Fixed $schema "currentColor" 'current color normalization is missing'
Assert-Fixed $schema "stage_end" 'stage end normalization is missing'
Assert-Fixed $schema "auto" 'gcolor auto normalization is missing'
Assert-Fixed $schema "anten" 'anten normalization is missing'
Assert-Fixed $schema "normalizeAntenPattern" 'anten pattern normalization is missing'
Assert-Fixed $schema "SUMAHO_CHARAS" 'schema sumaho character list is missing'
Assert-Fixed $schema "normalizeSumahoChara" 'schema sumaho normalization is missing'
Assert-Fixed $schema "sumaho" 'schema sumaho log normalization is missing'
Assert-Fixed $schema "INITIAL_ICATCHES" 'schema initial icatch list is missing'
Assert-Fixed $schema "normalizeInitialIcatch" 'schema initial icatch normalization is missing'
Assert-Fixed $schema "icatch" 'schema initial icatch log normalization is missing'
Assert-Fixed $schema "hadWin" 'schema hadWin normalization is missing'
Assert-Fixed $schema "autoColorBoundary" 'schema auto color boundary normalization is missing'
Assert-Fixed $schema "sessionMoney:normalizeSessionMoney" 'sessionMoney default normalization is missing'
Assert-Fixed $schema "function normalizeSessionMoney" 'normalizeSessionMoney definition is missing'
Assert-Fixed $schema "startRealG" 'schema start real G normalization is missing'
Assert-Fixed $schema "startLcdG" 'schema start lcd G normalization is missing'
Assert-Fixed $schema "initialMedalInAmount" 'schema initial medal input normalization is missing'
Assert-Fixed $schema "initialMedalInSource" 'schema initial medal source normalization is missing'
Assert-Fixed $schema "currentMochidama" 'schema current mochidama normalization is missing'
Assert-Fixed $schema "currentSaipurei" 'schema current saipurei normalization is missing'
Assert-Fixed $schema "balanceVersion" 'schema balance version normalization is missing'
Assert-Fixed $schema "legacy_trig" 'legacy trig preservation is missing'
Assert-Fixed $schema "money" 'money log normalization is missing'
Assert-Fixed $schema "medalIn" 'schema medalIn op normalization is missing'
Assert-Fixed $schema "balanceSync" 'schema balanceSync op normalization is missing'
Assert-Fixed $schema "source" 'schema medal source normalization is missing'
Assert-Fixed $schema "usedUnknown" 'schema unknown medal usage normalization is missing'
Assert-Fixed $schema "collectEnd" 'money collectEnd op is missing'
Assert-Fixed $schema "exitRealG" 'schema exitRealG normalization is missing'
Assert-Fixed $schema "root.normalizeSf6Export=api.normalizeSf6Export" 'browser global normalizer export is missing'

Assert-Fixed $agents "示唆入力は発生契機のフローに組み込む" 'AGENTS hint timing principle is missing'
Assert-Fixed $agents "各示唆・演出がどのタイミングで発生するか" 'AGENTS hint timing inventory rule is missing'
Assert-Fixed $agents "発生契機から切り離した独立入力ボタン" 'AGENTS independent hint button warning is missing'
Assert-Fixed $agents "DCとストリートジャッジの分離" 'AGENTS SF6 v3.4 lesson marker is missing'
Assert-Fixed $agents "発生契機が複数ある示唆" 'AGENTS multi-trigger hint rule is missing'
Assert-Fixed $agents "判定ロジックのスコープ" 'AGENTS state rollback scope rule is missing'
Assert-Fixed $agents "リセット時刻以降のログだけを対象" 'AGENTS auto trigger duplicate scope marker is missing'
Assert-Fixed $agents "シート内の入力順は実機の進行順" 'AGENTS sheet input order rule is missing'
Assert-Fixed $agents "ボーナス種別 → 枚数 → 終了画面 → クレジット" 'AGENTS SF6 win sheet order example is missing'

"sf6-record static checks passed"
